### ISSUE TITLE
Dependency on New-Runspace function

### ISSUE THREAD

**Issue by jimpallomeni** [EvotecIT/PSBlackListChecker#1]
Error:
New-Runspace : The term 'New-Runspace' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At C:\Program Files\WindowsPowerShell\Modules\PSBlackListChecker\0.7\Public\Search-Blacklist.ps1:52 char:17
+         $pool = New-Runspace -MaxRunspaces $maxRunspaces -Verbose:$Ve ...
+                 ~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (New-Runspace:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

Fix:
Install-Module PSSharedGoods

**Comment by PrzemyslawKlys** [comment]
Hi,

There are few more dependencies:

```powershell
    # Modules that must be imported into the global environment prior to importing this module
    RequiredModules   = @('PSSharedGoods', 'PSWriteColor', 'PSSlack', 'PSTeams')
```

That is part of .psd1 file and if you're using `Install-Module PSBlackListChecker` you should get those required modules installed straight from PSGallery with the module. It didn't happen? Or did you downloaded this module straight from GitHub?

**Comment by jimpallomeni** [comment]
Hi,

My POSH version:
PS C:\temp> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.17134.407
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.17134.407
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

After doing the update-module on the other issue, it seemed to install all the dependencies now so I am not sure what happened. Maybe my computer was being weird or the repository wasn't available when I installed your module. Thanks again!
