### ISSUE TITLE
email options

### ISSUE THREAD

**Issue by lucwuyts** [EvotecIT/PSBlackListChecker#6]
In the article:
https://evotec.xyz/psblacklistchecker-added-discord-support/
you put the option  EmailAlways inside the $ReportOptions.NotificationsEmail settings.
But in the source of  "Start-ReportBlackLists"  you look for this setting in $ReportOptions

**Comment by PrzemyslawKlys** [comment]
Yes and no. I'm supporting both options.

```
    if ($null -eq $ReportOptions.NotificationsEmail) {
        # Not upgraded config / Legacy config
        $ReportOptions.NotificationsEmail = @{
            Use                          = $true
            EmailPriorityWhenBlacklisted = $ReportOptions.EmailPriorityWhenBlacklisted
            EmailPriorityStandard        = $ReportOptions.EmailPriorityStandard
            EmailAllResults              = $ReportOptions.EmailAllResults
            EmailAlways                  = $ReportOptions.EmailAlways
        }
    }
```

I've decided that it's not worth breaking someone's config just because I changed my mind. So I support the old version and the new version as well.

**Comment by lucwuyts** [comment]
Ok, it didn't work here, so i started looking at the source.
But maybe i have a old version or have made a syntax error....

**Comment by PrzemyslawKlys** [comment]
Well, let me know if it still won't work. Maybe I made mistake. The idea is that it should work with old and new config.

**Comment by lucwuyts** [comment]
Maybe i do not have the latest version of the module?
I have version 0.8.2 of PSBlackListChecker

On line 391 there is no check for the EmailAlways parameter in the Notificationsmail options

This is this  line:
`   if ($ReportOptions.NotificationsEmail.Use) {if ($ReportOptions.EmailAlways -eq $true -or $BlackListCheck.IsListed -contains $true) {if ($FormattingParameters.CompanyBranding.Inline) {$SendMail = Send-Email -EmailParameters $EmailParameters -Body $EmailBody -InlineAttachments @{logo = $FormattingParameters.CompanyBranding.Logo} -Verbose} else {$SendMail = Send-Email -EmailParameters $EmailParameters -Body $EmailBody}}`

**Comment by PrzemyslawKlys** [comment]
Ok, should be fixed now. Please do an update

```powershell
Update-Module PSBlackListChecker
```

**Comment by lucwuyts** [comment]
Yes, working perfect!
Thanks!
