### ISSUE TITLE
blacklist bl.eamilbasuara.org is dead and should be removed from list

### ISSUE THREAD

**Issue by StefanoN-Infotronics** [EvotecIT/PSBlackListChecker#8]
https://www.dnsbl.com/2019/10/status-of-blemailbasuraorg-dead.html

Status of bl.emailbasura.org: DEAD
The DNSBL Email Basura is no more. Email Basura ("Trash" in Spanish) appears to have been online since at least 2004, according to the Internet Archive. This anti-spam blacklist's DNSBL zone was "bl.emailbasura.org."

The domain emailbasura.org seems to have expired and been purchased by a domain speculator. The domain has wildcard DNS entries, meaning that any use of the old DNSBL zone in your email server may result in your server blocking all inbound mail. You don't want that! Remove the DNSBL zone "bl.emailbasura.org" from your mail server configuration as soon as possible.
Posted by Al Iverson on Wednesday, October 30, 2019 
Labels: bl.emailbasura.org, dead dnsbls, dnsbl

**Comment by PrzemyslawKlys** [comment]
Tnx released a new version!
